### ISSUE TITLE
Configs for SSF adapter models not available

### ISSUE THREAD

**Issue by drimpossible** [RanPAC/RanPAC#4]
Hi! Reopening this as I ran into problems with the SSF adapter model -- configs for training them seem to not be available.
Could you provide a fix for this?

I'm attaching the log for reference
```
2024-01-17 20:54:51,168 [_builder.py] => No pretrained configuration specified for vit_base_patch16_224_in21k model. Using a default. Please add a config to the model pretrained_cfg registry or pass explicitly.
Traceback (most recent call last):
  File "/media/bayesiankitten/Hanson/RanPAC-main/main.py", line 18, in <module>
    main()
  File "/media/bayesiankitten/Hanson/RanPAC-main/main.py", line 15, in main
    train(args)
  File "/media/bayesiankitten/Hanson/RanPAC-main/trainer.py", line 20, in train
    ave_acc=_train(args)
  File "/media/bayesiankitten/Hanson/RanPAC-main/trainer.py", line 54, in _train
    model = Learner(args)
  File "/media/bayesiankitten/Hanson/RanPAC-main/RanPAC.py", line 77, in __init__
    self._network = SimpleVitNet(args, True)
  File "/media/bayesiankitten/Hanson/RanPAC-main/inc_net.py", line 196, in __init__
    super().__init__(args, pretrained)
  File "/media/bayesiankitten/Hanson/RanPAC-main/inc_net.py", line 154, in __init__
    self.convnet = get_convnet(args, pretrained)
  File "/media/bayesiankitten/Hanson/RanPAC-main/inc_net.py", line 87, in get_convnet
    model=timm.create_model("vit_base_patch16_224_in21k_ssf",pretrained=True, num_classes=0)
  File "/media/bayesiankitten/Alexander/anaconda3/envs/py310/lib/python3.10/site-packages/timm/models/_factory.py", line 117, in create_model
    model = create_fn(
  File "/media/bayesiankitten/Hanson/RanPAC-main/petl/vision_transformer_ssf.py", line 857, in vit_base_patch16_224_in21k_ssf
    model = _create_vision_transformer('vit_base_patch16_224_in21k', pretrained=pretrained, **model_kwargs)
  File "/media/bayesiankitten/Hanson/RanPAC-main/petl/vision_transformer_ssf.py", line 738, in _create_vision_transformer
    pretrained_custom_load='npz' in pretrained_cfg['url'],
TypeError: 'PretrainedCfg' object is not subscriptable

```

**Comment by markmcd-aiml** [comment]
@drimpossible , I am unable to reproduce this problem in my current python conda environment. My understanding is that pre-trained_cfg is part of the model downloaded from timm.  My best guess is you are using an older (or maybe newer) version of timm. I am using timm==0.6.12. Can you try changing to that and see if he problem persists?

**Comment by drimpossible** [comment]
Ah yep, that's correct. I was using a newer version of timm==0.9, downgraded and it worked!~ Thanks.

**Comment by markmcd-aiml** [comment]
Thanks for  confirming that. At some point I'll see what can be done to make everything work with different timm versions...

**Comment by drimpossible** [comment]
Hi! Embarassingly, I reproduced CIFAR100 which didn't require the SSF models. 
Running ImageNet-A which does require ssf models, the error persists. It was not a timm package issue.

```
(py310) RanPAC-main > python
Python 3.10.12 (main, Jul  5 2023, 18:54:27) [GCC 11.2.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import timm
>>> timm.__version__
'0.6.12'
>>> exit()
(py310) RanPAC-main > bash reproduce_gpu_1.sh 
2024-01-21 13:04:13,054 [trainer.py] => Starting new run
2024-01-21 13:04:13,055 [trainer.py] => ID: 7
2024-01-21 13:04:13,055 [trainer.py] => dataset: imageneta
2024-01-21 13:04:13,055 [trainer.py] => shuffle: True
2024-01-21 13:04:13,055 [trainer.py] => init_cls: 2
2024-01-21 13:04:13,055 [trainer.py] => increment: 1
2024-01-21 13:04:13,055 [trainer.py] => model_name: ssf
2024-01-21 13:04:13,055 [trainer.py] => convnet_type: pretrained_vit_b16_224_in21k_ssf
2024-01-21 13:04:13,055 [trainer.py] => device: [device(type='cuda', index=0)]
2024-01-21 13:04:13,055 [trainer.py] => seed: 1993
2024-01-21 13:04:13,055 [trainer.py] => batch_size: 48
2024-01-21 13:04:13,055 [trainer.py] => tuned_epoch: 20
2024-01-21 13:04:13,055 [trainer.py] => body_lr: 0.01
2024-01-21 13:04:13,055 [trainer.py] => head_lr: 0.01
2024-01-21 13:04:13,055 [trainer.py] => weight_decay: 0.0005
2024-01-21 13:04:13,055 [trainer.py] => min_lr: 0.0
2024-01-21 13:04:13,055 [trainer.py] => use_RP: True
2024-01-21 13:04:13,055 [trainer.py] => M: 10000
2024-01-21 13:04:13,055 [trainer.py] => use_input_norm: False
2024-01-21 13:04:13,055 [trainer.py] => do_not_save: False
Traceback (most recent call last):
  File "/media/bayesiankitten/Hanson/RanPAC-main/main.py", line 18, in <module>
    main()
  File "/media/bayesiankitten/Hanson/RanPAC-main/main.py", line 15, in main
    train(args)
  File "/media/bayesiankitten/Hanson/RanPAC-main/trainer.py", line 20, in train
    ave_acc=_train(args)
  File "/media/bayesiankitten/Hanson/RanPAC-main/trainer.py", line 54, in _train
    model = Learner(args)
  File "/media/bayesiankitten/Hanson/RanPAC-main/RanPAC.py", line 77, in __init__
    self._network = SimpleVitNet(args, True)
  File "/media/bayesiankitten/Hanson/RanPAC-main/inc_net.py", line 196, in __init__
    super().__init__(args, pretrained)
  File "/media/bayesiankitten/Hanson/RanPAC-main/inc_net.py", line 154, in __init__
    self.convnet = get_convnet(args, pretrained)
  File "/media/bayesiankitten/Hanson/RanPAC-main/inc_net.py", line 87, in get_convnet
    model=timm.create_model("vit_base_patch16_224_in21k_ssf",pretrained=True, num_classes=0)
  File "/media/bayesiankitten/Alexander/anaconda3/envs/py310/lib/python3.10/site-packages/timm/models/factory.py", line 71, in create_model
    model = create_fn(pretrained=pretrained, pretrained_cfg=pretrained_cfg, **kwargs)
  File "/media/bayesiankitten/Hanson/RanPAC-main/petl/vision_transformer_ssf.py", line 857, in vit_base_patch16_224_in21k_ssf
    model = _create_vision_transformer('vit_base_patch16_224_in21k', pretrained=pretrained, **model_kwargs)
  File "/media/bayesiankitten/Hanson/RanPAC-main/petl/vision_transformer_ssf.py", line 732, in _create_vision_transformer
    print(pretrained_cfg['url'])
UnboundLocalError: local variable 'pretrained_cfg' referenced before assignment
(py310) RanPAC-main > 
```

**Comment by drimpossible** [comment]
(Sorry wanted to close the issue but reopened it)

**Comment by markmcd-aiml** [comment]
So its all good now @drimpossible ?

**Comment by drimpossible** [comment]
Yes, all good! It ran
